apiVersion: v1
kind: Secret
metadata:
  name: {{ include "classification-api.fullname" . }}-env
  labels: {{ include "classification-api.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.config.auth.enabled }}
data:
  APIV3_API_KEY_ADMIN: {{ required "config.auth.adminKey is required when config.auth.enabled" .Values.config.auth.adminKey | b64enc | quote }}
  APIV3_API_KEY_READONLY: {{ required "config.auth.readonlyKey is required when config.auth.enabled" .Values.config.auth.readonlyKey | b64enc | quote }}
{{- else }}
data: {}
{{- end }}
